apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  host: "YOUR_POSTGRES_HOST.postgres.database.azure.com"
  port: "5432"
  name: "cloudjobhunt"
  user: "YOUR_USERNAME@YOUR_POSTGRES_HOST"
  password: "YOUR_PASSWORD"
